modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "worldwarps"
version = "${version}"
displayName = "WorldWarps"
authors = "VeiTr"
description = '''
A simple mod that allows you to create warps to different locations in the world.
'''
#logoFile = ""

[[dependencies.worldwarps]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldwarps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
