modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/VeiTrr/WorldWarps/issues"
license = "MIT"

[[mods]]
modId = "worldwarps"
version = "${version}"
displayName = "WorldWarps"
authors = "VeiTr"
description = '''
A mod that allows you to create warps to different locations in the world.
'''
logoFile = "assets/worldwarps/icon.png"
displayTest = "NONE"

[[dependencies.worldwarps]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldwarps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.4]"
ordering = "NONE"
side = "BOTH"
